---
- name: Gather facts if not available
  setup:
  when: ansible_env is not defined
  delegate_to: localhost
  run_once: true

- name: Create callback plugins directory
  file:
    path: "{{ ansible_user_dir | default(ansible_env.HOME + '/.ansible') }}/plugins/callback"
    state: directory
    mode: '0755'
  delegate_to: localhost
  run_once: true

- name: Install prettify callback plugin
  copy:
    src: prettify.py
    dest: "{{ ansible_user_dir | default(ansible_env.HOME + '/.ansible') }}/plugins/callback/prettify.py"
    mode: '0644'
  delegate_to: localhost
  run_once: true

