---
- name: Display prettify installation success
  debug:
    msg: |
      ✨ Prettify callback plugin installed to ~/.ansible/plugins/callback/prettify.py

      Ready to beautify your Ansible output!